name: Continuous Integration
on: 
  push:
    paths-ignore: 'README.md'
  pull_request:
    types: [opened, reopened]
    paths-ignore: 'README.md'

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: docker build --target test --tag todo-app:test .
    - name: test
      id: test
      run: | 
        if docker run todo-app:test | grep -q 'FAILURES'; then
          echo "retest=true" >> $GITHUB_OUTPUT
        fi
    - name: output
      if: always()
      run: | 
        echo ${{ steps.test.outputs.retest }}
    - name: retest
      id: retest
      if: ${{ failure() && steps.test.outputs.retest == 'true' }}
      run: | 
        docker run todo-app:test
    - name: slack
      if: always() && steps.test.outcome != 'success' && steps.retest.outcome != 'success'
      uses: slackapi/slack-github-action@v1.27.0
      with:
        payload: |
          {"text": "E2E test failure: detox tests have failed"}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  push-and-deploy:
    name: Push to Docker Hub and deploy
    runs-on: ubuntu-latest
    needs: build-and-test
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'}}
    steps: 
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: docker build --target production --tag katielht/todo-app:prod .
    - run: docker push katielht/todo-app:prod
    - run: curl -dH -X POST '${{ secrets.AZURE_WEBHOOK }}'



