name: Continuous Integration
on: 
  push:
    paths-ignore: 'README.md'
  pull_request:
    types: [opened, reopened]
    paths-ignore: 'README.md'

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker build --target test --tag todo-app:test .
    - run: docker run todo-app:test
  
  push-and-deploy:
    name: Push to Docker Hub and deploy
    runs-on: ubuntu-latest
    needs: build-and-test
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/exercise-10'}}
    steps: 
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: docker build --target production --tag katielht/todo-app:prod .
    - run: docker push katielht/todo-app:prod
    - run: curl -dH -X POST '${{ secrets.AZURE_WEBHOOK }}'



